// app/src/app/admin/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {UsersService} from "../../services/users.service";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  clicked: any;
  data: FormGroup = this.formBuilder.group({
    username: ['', Validators.required],
    password: ['', Validators.required]
  });
  private submitted: Boolean = false;
  loading: boolean = false;

  constructor(
    private readonly titleService: Title,
    private readonly formBuilder: FormBuilder,
    private readonly userService: UsersService,
  ) {
  }

  ngOnInit(): void {
    this.titleService.setTitle('Login');
  }

  submit() {
    this.clicked = true;
    if (this.data.valid && !this.submitted) {
      this.submitted = true;
      this.loading = true;
      this.userService.login(this.data.value).subscribe({
        next: (res) => {
          if (res.error){
            if (res.error == 'username'){
              this.data.get('username')?.setErrors({'username': 'Invalid username or email.'});
            } else if (res.error == 'password'){
              this.data.get('password')?.setErrors({'password': 'Invalid password.'});
            }
          }
          console.log(res);
          this.loading = false;
          this.submitted = false;
        },
        error: (err) => {
          console.log(err);
          this.loading = false;
          this.submitted = false;
        }
      });
    }
  }
}

<div class="admin-container">
  <mat-card class="col-md-6">
    <mat-card-title style="text-align: center">Login</mat-card-title>
    <mat-card-content>
      <form [formGroup]="data" (ngSubmit)="submit()">
        <app-form-group label="Username or Email" fcn="username" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="Password" fcn="password" type="password" [clicked]="clicked"></app-form-group>
        <div class="align-right">
          <button mat-raised-button color="primary" type="submit" [disabled]="!data.valid">Login</button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
<app-loading *ngIf="loading"></app-loading>

// react-app/src/auth/login/login.jsx
import React from "react";
import FormGroup from "../../commons/form-group/form-group";
import Validators from "../../validators/validators";
import ReactiveForm from "../../reactive-form/reactive-form";
import FormControl from "../../reactive-form/form-control";
import {Link, Navigate} from "react-router-dom";
import UsersService from "../../services/users.service";
import Loading from "../../commons/loading/loading";

export default class Login extends React.Component {
    data = new ReactiveForm({
        username: new FormControl('', [Validators.required]),
        password: new FormControl('', [Validators.required])
    });

    state = {
        clicked: false,
        navigate_to_admin: UsersService.is_logged_in,
        loading: false
    }

    submit(e) {
        e.preventDefault();
        this.setState({clicked: true}, () => {
            if (this.data.valid && !this.state.submitted) {
                this.setState({submitted: true, loading: true}, () => {
                    UsersService.login(this.data.value).then(res => {
                        if (res.error) {
                            if (res.error === 'username') {
                                this.data.get('username').set_error({username: 'Invalid username or email.'})
                            } else if (res.error === 'password') {
                                this.data.get('password').set_error({username: 'Invalid password.'})
                            } else {
                                console.trace(this);
                                throw new DOMException('Contact Server Admin')
                            }
                            this.setState({submitted: false, loading: false});
                        } else if (res.token) {
                            UsersService.set_token(res.token)
                            UsersService.$is_logged_in.emit(true);
                            this.setState({navigate_to_admin: true})
                        }
                    });
                });
            }
        });
    }

    render() {
        return (
            <div id="login">
                {this.state.navigate_to_admin ? <Navigate to='/admin'/> : null}
                <div className="col-md-6 text-center">
                    <div className="card mt-3">
                        <div className="card-header">Login</div>
                        <div className="card-body">
                            <form onSubmit={this.submit.bind(this)}>
                                <FormGroup clicked={this.state.clicked} name='Username or email'
                                           form_control={this.data.get('username')}/>
                                <FormGroup type='password' clicked={this.state.clicked} name='Password' className='mt-3'
                                           form_control={this.data.get('password')}/>
                                <div className="mt-3" style={{display: 'flex', justifyContent: 'space-between'}}>
                                    <Link to='/' className='btn btn-primary'>Home</Link>
                                    <button type='submit' className='btn btn-primary'>Login</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {this.state.loading ? <Loading/> : null}
            </div>
        )
    }
}
