// app/src/app/home/experience/experience.component.ts
import { Component, OnInit } from '@angular/core';
import {ExperienceService} from "../../services/experience.service";

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.scss']
})
export class ExperienceComponent implements OnInit {
  loading = true;
  experiences!: { frontend: { title: string; experience: string }[]; backend: { title: string; experience: string }[] };

  constructor(
    private readonly experienceService: ExperienceService
  ) { }

  ngOnInit(): void {
    this.experienceService.index.subscribe({
      next: (experiences) => {
        this.experiences = experiences;
        this.loading = false;
      },
      error: (err) => {
        console.error(err);
        this.loading = false;
      }
    });
  }

}

<section id="experience">
  <h5>The Skills I Have</h5>
  <h2>My Experience</h2>
  <div class="container">
    <div class="frontend" *ngIf="experiences?.frontend?.length">
      <h3>Frontend Development</h3>
      <div class="content">
        <article class="details" *ngFor="let data of experiences?.frontend">
          <mat-icon>verified</mat-icon>
          <div><h4>{{data.title}}</h4>
            <small class="text-light">{{data.experience}}</small></div>
        </article>
      </div>
    </div>
    <div class="backend" *ngIf="experiences?.backend?.length">
      <h3>Backend Development</h3>
      <div class="content">
        <article class="details" *ngFor="let data of experiences?.backend">
          <mat-icon>verified</mat-icon>
          <div>
            <h4>{{data.title}}</h4>
            <small class="text-light">{{data.experience}}</small>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>
<app-loading *ngIf="loading"></app-loading>

// react-app/src/home/experience/experience.jsx
import React from "react";
import "./experience.scss";
export default class Experience extends React.Component {
    state = {
        experiences: null
    }
    render() {
        return (
            <>
                {this.props.experiences?.frontend?.length || this.props.experience?.backend?.length ? (<section id="experience">
                    <h5>The Skills I Have</h5>
                    <h2>My Experience</h2>
                    <div className="container">
                        {
                            this.props.experiences?.frontend?.length ?
                                (<div className="frontend">
                                    <h3>Frontend Development</h3>
                                    <div className="content">
                                        {this.props.experiences?.frontend?.map((experience, index) => {
                                            return (
                                                <article className="details" key={index}>
                                                    <i className="fa-solid fa-certificate"></i>
                                                    <div>
                                                        <h4>{experience.title}</h4>
                                                        <small className="text-light">{experience.experience}</small>
                                                    </div>
                                                </article>
                                            )
                                        })}
                                    </div>
                                </div>) :
                                null
                        }
                        {this.props.experiences?.backend?.length ?
                            (<div className="backend">
                                <h3>Backend Development</h3>
                                <div className="content">
                                    {this.props.experiences?.backend?.map((experience, index) => {
                                        return (
                                                <article className="details" key={index}>
                                                    <i className="fa-solid fa-certificate"></i>
                                                    <div>
                                                        <h4>{experience.title}</h4>
                                                        <small className="text-light">{experience.experience}</small>
                                                    </div>
                                                </article>
                                        )
                                    })}
                                </div>
                            </div>) :
                            null
                        }
                    </div>
                </section>) : null}
                {/* <app-loading></app-loading> */}
            </>

        )
    }
}
