// react-app/src/admin/experiences/new/new.jsx
import React from "react";
import FormGroup from "../../../commons/form-group/form-group";
import ReactiveForm from "../../../reactive-form/reactive-form";
import FormControl from "../../../reactive-form/form-control";
import Validators from "../../../validators/validators";
import {Link, Navigate} from "react-router-dom";
import Loading from "../../../commons/loading/loading";
import AdminService from "../../../services/admin.service";
import UsersService from "../../../services/users.service";

export default class New extends React.Component {
    data = new ReactiveForm({
        title: new FormControl('', [Validators.required]),
        experience: new FormControl("", [Validators.required]),
        category: new FormControl("", [Validators.required])
    });

    state = {
        clicked: false,
        loading: false,
        submitted: false,
        go_back: false
    }

    componentDidMount() {
        document.title = 'Admin | Experience | New'
    }

    render() {
        return (
            <div id="new">
                {this.state.go_back ? <Navigate to={'../'}/> : null}
                {!UsersService.is_logged_in ? <Navigate to={'/auth/login'}/> : null}
                <div className="container align-center">
                    <div className="card mt-3 col-md-6">
                        <div className="card-header">New Experience</div>
                        <div className="card-body">
                            <form onSubmit={e => this.submit(e)}>
                                <FormGroup clicked={this.state.clicked} name={'Title'}
                                           form_control={this.data.get('title')}/>
                                <FormGroup clicked={this.state.clicked} className={'mt-3'} name={'Experience'}
                                           type={'number'} form_control={this.data.get('experience')}/>
                                <FormGroup options={[
                                    {
                                        name: 'Frontend',
                                        value: 'frontend'
                                    },
                                    {
                                        name: 'Backend',
                                        value: 'backend'
                                    }
                                ]} type={'select'} clicked={this.state.clicked} className={'mt-3'} name={'Category'}
                                           form_control={this.data.get('category')}/>
                                <div className="align-right mt-3">
                                    <Link to={'../'} className={'btn'}>Back</Link>
                                    <button type={'submit'} className={'btn btn-primary'}>Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {this.state.loading ? <Loading/> : null}
            </div>
        )
    }

    /**
     * @param {Event} e
     */
    submit(e) {
        e.preventDefault();
        this.setState({clicked: true}, () => {
            if (this.data.valid && !this.state.submitted) {
                this.setState({loading: true, submitted: true}, () => {
                    AdminService.experiences.new(this.data.value).then(r => {
                        if (r.success)
                            this.setState({go_back: true});
                        else {
                            this.setState({loading: false, submitted: false});
                        }
                    });
                });
            }
        });
    }
}

// app/src/app/admin/experience/new/new.component.ts
import { Component, OnInit } from '@angular/core';
import {Title} from "@angular/platform-browser";
import {Helpers} from "../../../helpers/Helpers";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {AsyncValidator} from "../../../helpers/AsyncValidator";
import {environment} from "../../../../environments/environment";
import {AdminService} from "../../../services/admin.service";
import {PlatformLocation} from "@angular/common";

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.scss']
})
export class NewComponent implements OnInit {
  category_opts: { account: string; value: string; }[] = ['frontend', 'backend'].map(x => ({ account: Helpers.titlecase(x), value: x }));
  clicked: boolean = false;
  data: FormGroup = new FormGroup({
    title: new FormControl('', Validators.required, AsyncValidator.uniq(environment.api + '/experience/uniq', 'title', 'Title already exists')),
    experience: new FormControl('', Validators.required),
    category: new FormControl('', Validators.required),
  });
  private submitted: Boolean = false;
  loading: boolean = false;

  constructor(
    private readonly title: Title,
    private readonly adminService:AdminService,
    private readonly platformLocation: PlatformLocation
  ) { }

  ngOnInit(): void {
    this.title.setTitle('New Experience');
  }

  submit() {
    this.clicked = true;
    if (this.data.valid && !this.submitted) {
      this.submitted = true;
      this.loading = true;
      this.adminService.experience.new(this.data.value).subscribe({
        next: (res) => {
          if (res.error) {
            alert(res.error);
            this.submitted = false;
            this.loading = false;
          } else if (res.success) {
            this.platformLocation.back();
          }
        },
        error: (err) => {
          this.loading = false;
          this.submitted = false;
          console.error(err);
        }
      });
    }
  }

  back() {
    this.platformLocation.back();
  }
}

<div class="admin-container">
  <mat-card>
    <mat-card-title style="text-align: center;">
      New Experience
    </mat-card-title>
    <mat-card-content>
      <form [formGroup]="data" (ngSubmit)="submit()">
        <app-form-group label="Title" fcn="title" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="Experience" fcn="experience" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="Category" fcn="category" type="select" [clicked]="clicked" [opts]="category_opts"></app-form-group>
        <div class="align-right">
          <button mat-raised-button color="warn" (click)="back()" type="button">Back</button>
          <button mat-raised-button color="primary" type="submit">Submit</button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
<app-loading *ngIf="loading"></app-loading>
