// react-app/src/commons/page-not-found/page-not-found.jsx
import React from 'react';
import './page-not-found.scss';
import {Link} from "react-router-dom";

export default class PageNotFound extends React.Component{
    render() {
        return (
            <div id="page-not-found">
                <h1>404 Page Not Found</h1>
                <p>The page you are trying to get is not in our database. If you think this is a mistake from us, please make contact to
                    our server administrator.</p>
                <Link to='/' className='btn'>Home</Link>
            </div>
        );
    }
}

// app/src/app/commons/page-not-found/page-not-found.component.ts
import { Component, OnInit } from '@angular/core';
import {Title} from "@angular/platform-browser";

@Component({
  selector: 'app-page-not-found',
  templateUrl: './page-not-found.component.html',
  styleUrls: ['./page-not-found.component.scss']
})
export class PageNotFoundComponent implements OnInit {

  constructor(
    private readonly title: Title
  ) { }

  ngOnInit(): void {
    this.title.setTitle('Page Not Found')
  }

}

<h1>404 Page Not Found</h1>
<p>The page you are trying to get is not in our database. If you think this is a mistake from us, please make contact to
  our server administrator.</p>
