// app/src/app/admin/testimonials/testimonials.component.ts
import { Component, OnInit } from '@angular/core';
import {Title} from "@angular/platform-browser";
import {PlatformLocation} from "@angular/common";
import {AdminService} from "../../services/admin.service";
import {environment} from "../../../environments/environment";

@Component({
  selector: 'app-testimonials',
  templateUrl: './testimonials.component.html',
  styleUrls: ['./testimonials.component.scss']
})
export class TestimonialsComponent implements OnInit {
  loading: boolean = true;
  testimonials: { id: string; name: string; description: string; image_link: string }[] = [];
  api: string = environment.api;

  constructor(
    private readonly titleService: Title,
    private readonly platformLocation: PlatformLocation,
    private readonly adminService: AdminService
  ) { }

  ngOnInit(): void {
    this.titleService.setTitle('Testimonials');
    this.fetch();
  }

  private fetch() {
    this.adminService.testimonial.index().subscribe({
      next: (data) => {
        this.testimonials = data;
        this.loading = false;
      },
      error: (err) => {
        console.error(err);
        this.loading = false;
      }
    });
  }

  back() {
    this.platformLocation.back();
  }

  delete(id: string) {
    if (confirm('Are you sure you want to delete this testimonial?')) {
      this.loading = true;
      this.adminService.testimonial.delete(id).subscribe({
        next: (data) => {
          if (data.success) {
            this.fetch();
          }else {
            alert(data.error);
            this.loading = false;
          }
        },
        error: (err) => {
          console.error(err);
          this.loading = false;
        }
      });
    }
  }
}

<div class="admin-container">
  <div style="display:flex;align-items:center;justify-content:space-between;">
    <h2>Testimonials</h2>
    <div class="align-right">
      <a routerLink="new" mat-raised-button color="primary">New</a>
      <button mat-raised-button color="warn" (click)="back()">Back</button>
    </div>
  </div>
  <div class="table-responsive" style="margin-top: .75em;">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Image</th>
        <th></th>
      </tr>
      <tr *ngFor="let testimonial of testimonials">
        <td>{{testimonial.id}}</td>
        <td>{{testimonial.name}}</td>
        <td>{{testimonial.description}}</td>
        <td><img [src]="api + testimonial.image_link" width="100" height="100" style="aspect-ratio: 1/1"/></td>
        <td>
          <button mat-mini-fab color="warn" (click)="delete(testimonial.id)"><mat-icon>delete</mat-icon></button>
        </td>
    </table>
  </div>
</div>
<app-loading *ngIf="loading"></app-loading>

// react-app/src/admin/testimonials/testimonials.jsx
import React from "react";
import {Link, Route, Routes} from "react-router-dom";
import PageNotFound from "../../commons/page-not-found/page-not-found";
import Loading from "../../commons/loading/loading";
import AdminService from "../../services/admin.service";
import Config from "../../Config";

class Component extends React.Component {
    state = {
        data: [],
        loading: true
    }

    componentDidMount() {
        document.title = 'Admin | Testimonials'
        AdminService.testimonials.index().then(r => {
            this.setState({loading: false, data: r});
        });
    }

    render() {
        return (
            <div id={'testimonials'}>
                <div className="container">
                    <h2 className="align-center mt-3">Testimonials</h2>
                    <div className="align-right mt-3">
                        <Link to={'new'} className={'btn btn-primary'}>New</Link>
                        <Link to={'../../'} className={'btn'}>Back</Link>
                    </div>
                    {this.state.data.length ?
                        <table className="table mt-3">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {this.state.data.map((row, i) => {
                                return (
                                    <tr key={i}>
                                        <td>{row.id}</td>
                                        <td>{row.name}</td>
                                        <td>{row.description}</td>
                                        <td><img style={{width: '150px'}} src={Config.api + row.image_link} alt={'broken'} /></td>
                                        <td>
                                            <button className={'btn btn-primary'} onClick={() => this.delete(row.id)}>Delete</button></td>
                                    </tr>
                                )
                            })}
                            </tbody>
                        </table> :
                        <p className="mt-3 align-center">No data available.</p>}
                </div>
                {this.state.loading ? <Loading/> : null}
            </div>
        );
    }

    /**
     * @param {string} id
     */
    delete(id){
        if (window.confirm('Are you sure you want to delete this testimonial?')) {
            this.setState({loading: true}, () => {
                AdminService.testimonials.delete(id).then(r => {
                    if (r.success) {
                        const data = this.state.data.filter(row => {
                            return row.id !== id
                        });
                    this.setState({loading: false, data});
                    }
                });
            });
        }
    }
}

export default class Testimonials extends React.Component {
    render() {
        return (
            <Routes>
                <Route path={''} element={<Component/>}/>

                <Route path={'*'} element={<PageNotFound/>}/>
            </Routes>
        );
    }
}
