// app/src/app/home/portfolio/portfolio.component.ts
import { Component, OnInit } from '@angular/core';
import {PortfolioService} from "../../services/portfolio.service";
import {environment} from "../../../environments/environment";

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.scss']
})
export class PortfolioComponent implements OnInit {
  loading: boolean = true;
  portfolios: { title: string; github_link: string; live_link: string; image_link: string }[] = [];
  api: string = environment.api;

  constructor(
    private readonly portfolioService: PortfolioService,
  ) { }

  ngOnInit(): void {
    this.portfolioService.index.subscribe({
      next: (portfolios) => {
        this.portfolios = portfolios;
        this.loading = false;
      },
      error: (err) => {
        console.error(err);
        this.loading = false;
      }
    });
  }

}

<section id="portfolio">
  <h5>My Recent Work</h5>
  <h2>Portfolio</h2>
  <div class="container">
    <article class="item" *ngFor="let portfolio of portfolios">
      <div class="item-image">
        <img src="{{api}}{{portfolio.image_link}}" alt="Broken {{portfolio.title}} image">
      </div>
      <h3>{{portfolio.title}}</h3>
      <div class="cta">
        <a *ngIf="portfolio.github_link" href="{{portfolio.github_link}}" target="_blank" class="btn">Github</a>
        <a *ngIf="portfolio.live_link" href="{{portfolio.live_link}}" target="_blank" class="btn btn-primary">Live</a>
      </div>
    </article>
  </div>
</section>
<app-loading *ngIf="loading"></app-loading>

// react-app/src/home/portfolio/portfolio.jsx
import React from "react";
import './portfolio.scss';
import Config from "../../Config.js";
export default class Portfolio extends React.Component {
    render() {
        if (this.props.portfolios?.length)
            return (
                <div id="portfolio">
                    <section id="portfolio">
                        <h5>My Recent Work</h5>
                        <h2>Portfolio</h2>
                        <div className="container">
                            {this.props.portfolios?.map((portfolio, index) => {
                                return (
                                    <article key={index} className="item" >
                                        <div className="item-image">
                                            <img src={Config.api + portfolio.image_link} alt="Broken {{portfolio.title}} image" />
                                        </div>
                                        <h3>{portfolio?.title}</h3>
                                        <div className="cta">
                                            {
                                                portfolio?.github_link ?
                                                    (<a href={portfolio?.github_link} target="_blank" className="btn">Github</a>) :
                                                    null
                                            }
                                            {
                                                portfolio?.live_link ?
                                                    (<a href={portfolio.live_link} target="_blank" className="btn btn-primary">Live</a>) :
                                                    null
                                            }
                                        </div>
                                    </article>
                                )
                            })}
                        </div>
                    </section>
                </div>
            )
        return (<></>)
    }
}
