// react-app/src/commons/loading/loading.jsx
import React from "react";
import './loading.scss';

export default class Loading extends React.Component {
    render() {
        return (
            <div id="loading" className="loading">
                <img src="assets/preloader3.gif" alt="preloader" />
                {this.props.percent ?<progress max="100" value={this.props.percent} ></progress> : null}
                {this.props.percent ? <h5>{this.props.percent}%</h5> : null}
            </div>

        )
    }
}

// app/src/app/commons/loading/loading.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.scss']
})
export class LoadingComponent implements OnInit {

  constructor() {
  }

  @Input() percent: number | null = null;

  ngOnInit(): void {
  }

}

<div class="loading">
  <img src="assets/preloader3.gif" alt="preloader">
  <progress *ngIf="percent" max="100" [value]="percent"></progress>
  <h5 *ngIf="percent">{{percent}}%</h5>
</div>
