// react-app/src/home/about/about.jsx
import React from "react";
import './about.scss';
import Config from "../../Config";
export default class About extends React.Component {

    render() {
        return (
            <div id="about">
                <section id="about">
                    <h5>Get To Know</h5>
                    <h2>About Me</h2>
                    <div className="container">
                        <div className="me">
                            <div className="me-image">
                                <img src={this.props.about_me_image ? Config.api + this.props.about_me_image :'/assets/me2.png'} alt="Broken me 2" />
                            </div>
                        </div>
                        <div className="content">
                            <div className="cards">
                                {
                                    this.props.experience ?
                                        (<article className="card" /* *ngIf="experience" */>
                                            <i className="fa-solid fa-trophy"></i>
                                            <h5>Experience</h5>
                                            <small>{this.props.experience}+ Years Working</small>
                                        </article>) :
                                        null
                                }
                                {
                                    this.props.clients ?
                                        (<article className="card" /* *ngIf="clients" */>
                                            <i className="fa-solid fa-people-group"></i>
                                            <h5>Clients</h5>
                                            <small>{this.props.clients}+ Worldwide Clients</small>
                                        </article>) :
                                        null
                                }
                                {
                                    this.props.projects ?
                                        (<article className="card" /* *ngIf="projects" */>
                                            <i className="fa-solid fa-folder-open"></i>
                                            <h5>Projects</h5>
                                            <small>{this.props.projects}+ Completed Projects</small>
                                        </article>) :
                                        null
                                }
                            </div>
                            <a href="#contact" className="btn btn-primary">Let's Talk</a>
                        </div>
                    </div>
                </section>

            </div>
        );
    }
}

// app/src/app/home/about/about.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent implements OnInit {

  constructor() {
  }

  @Input() about_me_image: string | null = null;
  @Input() experience: string | null = null;
  @Input() clients: string | null = null;
  @Input() projects: string | null = null;

  ngOnInit(): void {
  }

}

<section id="about">
  <h5>Get To Know</h5>
  <h2>About Me</h2>
  <div class="container">
    <div class="me">
      <div class="me-image">
        <img src="{{about_me_image ?? '../../../assets/me2.png'}}" alt="Broken me 2">
      </div>
    </div>
    <div class="content">
      <div class="cards">
        <article class="card" *ngIf="experience">
          <mat-icon>emoji_events</mat-icon>
          <h5>Experience</h5>
          <small>{{experience}}+ Years Working</small>
        </article>
        <article class="card" *ngIf="clients">
          <mat-icon>people</mat-icon>
          <h5>Clients</h5>
          <small>{{clients}}+ Worldwide Clients</small>
        </article>
        <article class="card" *ngIf="projects">
          <mat-icon>source</mat-icon>
          <h5>Projects</h5>
          <small>{{projects}}+ Completed Projects</small>
        </article>
      </div>
      <a href="#contact" class="btn btn-primary">Let's Talk</a>
    </div>
  </div>
</section>
