// react-app/src/home/testimonials/testimonials.jsx
import React from "react";
import './testimonials.scss';
import Config from "../../Config.js";

// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation } from 'swiper'

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';

export default class Testimonials extends React.Component {
    render() {
        if (this.props.testimonials?.length) {
            return (
                <section id="testimonials">
                    <h5>Review From Clients</h5>
                    <h2>Testimonials</h2>
                    <div className="container">
                        <Swiper modules={[Navigation]} navigation>
                            {/* <SwiperSlide>1</SwiperSlide>
                            <SwiperSlide>2</SwiperSlide>
                            <SwiperSlide>3</SwiperSlide> */}
                            {this.props.testimonials?.map((testimonial, index) => {
                                return (
                                    <SwiperSlide key={index} className="testimonial">
                                        <div className="avatar">
                                            <img src={Config.api + testimonial.image_link} alt="broken client avatar" />
                                        </div>
                                        <h5 className="name">{testimonial.name}</h5>
                                        <small className="review">
                                            {testimonial.description}
                                        </small>
                                    </SwiperSlide>
                                )
                            })}
                        </Swiper>
                    </div>
                </section>

            )
        }
        return <></>
    }
}

// app/src/app/home/testimonials/testimonials.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import SwiperCore, { Navigation } from "swiper";
import {TestimonialService} from "../../services/testimonial.service";
import {environment} from "../../../environments/environment";
SwiperCore.use([Navigation]);
@Component({
  selector: 'app-testimonials',
  templateUrl: './testimonials.component.html',
  styleUrls: ['./testimonials.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class TestimonialsComponent implements OnInit {
  private loading: boolean = true;
  testimonials: { name: string; description: string; image_link: string }[] = [];
  api: string = environment.api;

  constructor(
    private readonly testimonialService: TestimonialService
  ) { }

  ngOnInit(): void {
    this.testimonialService.index.subscribe({
      next: (testimonials) => {
        this.testimonials = testimonials;
        console.log(this.testimonials);
        this.loading = false;
      },
      error: (err) => {
        console.log(err);
        this.loading = false;
      }
    });
  }

}

<section id="testimonials">
  <h5>Review From Clients</h5>
  <h2>Testimonials</h2>
  <div class="container">
    <swiper [navigation]="true">
      <ng-template swiperSlide class="testimonial" *ngFor="let testimonial of testimonials">
        <div class="avatar">
          <img src="{{api}}{{testimonial.image_link}}" alt="broken client avatar">
        </div>
        <h5 class="name">{{testimonial.name}}</h5>
        <small class="review">
          {{testimonial.description}}
        </small>
      </ng-template>
    </swiper>
  </div>
</section>
