// react-app/src/admin/portfolios/new/new.jsx
import React from "react";
import ReactiveForm from "../../../reactive-form/reactive-form";
import FormControl from "../../../reactive-form/form-control";
import Validators from "../../../validators/validators";
import FormGroup from "../../../commons/form-group/form-group";
import Loading from "../../../commons/loading/loading";
import {Link, Navigate} from "react-router-dom";
import AdminService from "../../../services/admin.service";

export default class New extends React.Component {

    data = new ReactiveForm({
        title: new FormControl('', [Validators.required]),
        github_link: new FormControl(),
        live_link: new FormControl(),
        image: new FormControl('', [Validators.required])
    })

    state = {
        clicked: false,
        submitted: false,
        loading: false,
        go_back: false
    }

    render() {
        return (
            <div id={'new'}>
                {this.state.go_back ? <Navigate to={'../'}></Navigate> : null}
                <div className="container align-center">
                    <div className="card mt-3 col-md-6">
                        <div className="card-header">New Portfolio</div>
                        <div className="card-body">
                            <form onSubmit={e => this.submit(e)}>
                                <FormGroup clicked={this.state.clicked} name={'Title'}
                                           form_control={this.data.get('title')}/>
                                <FormGroup className={'mt-3'} clicked={this.state.clicked} name={'Github Link'}
                                           form_control={this.data.get('github_link')}/>
                                <FormGroup className={'mt-3'} clicked={this.state.clicked} name={'Live Link'}
                                           form_control={this.data.get('live_link')}/>
                                <FormGroup on_change={e => {
                                    this.image = e.target.files.item(0)
                                }} accept={'image/*'} className={'mt-3'} clicked={this.state.clicked}
                                           name={'Image'} type={'file'}
                                           form_control={this.data.get('image')}/>
                                <div className="align-right mt-3">
                                    <Link to={'../'} className={'btn'}>Back</Link>
                                    <button className={'btn btn-primary'}>Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                {this.state.loading ? <Loading/> : null}
            </div>
        );
    }

    /**
     * @param {Event<HTMLFormElement>} e
     */
    submit(e) {
        e.preventDefault();
        this.setState({clicked: true}, () => {
            if (this.data.valid && !this.state.submitted && this.image) {
                this.setState({submitted: true, loading: true}, () => {
                    const form_data = new FormData();
                    for (let name in this.data.value) {
                        if (name !== 'image') {
                            form_data.append(name, this.data.value[name])
                        }
                    }
                    form_data.append('image', this.image, this.image.name)
                    AdminService.portfolios.new(form_data).then(r => {
                        if (r.success) {
                            this.setState({go_back: true});
                        } else {
                            this.setState({submitted: false, loading: false});
                        }
                    });
                });
            }
        });
    }

    /**
     * @type {File}
     */
    image
}

// app/src/app/admin/portfolio/new/new.component.ts
import {Component, OnInit} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {PlatformLocation} from "@angular/common";
import {AdminService} from "../../../services/admin.service";

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.scss']
})
export class NewComponent implements OnInit {
  data: FormGroup = new FormGroup({
    title: new FormControl(null, Validators.required),
    github_link: new FormControl(null),
    live_link: new FormControl(null),
    image: new FormControl(null, Validators.required),
  });
  clicked: boolean = false;
  private file!: File;
  private submitted: Boolean = false;
  loading: boolean = false;

  constructor(
    private readonly titleService: Title,
    private readonly platformLocation: PlatformLocation,
    private readonly adminService: AdminService,
  ) {
  }

  ngOnInit(): void {
    this.titleService.setTitle('New portfolio');
  }

  change_file(event: Event) {
    this.file = (<HTMLInputElement>event.target).files!.item(0)!;
  }

  back() {
    this.platformLocation.back();
  }

  submit() {
    this.clicked = true;
    if (this.data.valid && !this.submitted) {
      this.submitted = true;
      this.loading = true;
      let formData = new FormData();
      formData.append('title', this.data.value.title);
      formData.append('github_link', this.data.value.github_link);
      formData.append('live_link', this.data.value.live_link);
      formData.append('image', this.file, this.file.name);
      this.adminService.portfolio.new(formData).subscribe({
        next: r => {
          console.log(r);
          this.loading = false;
          this.submitted = false;
        },
        error: e => {
          console.log(e);
          this.loading = false;
          this.submitted = false;
        }
      })
    }
  }
}

<div class="admin-container">
  <mat-card>
    <mat-card-title style="text-align: center">New Portfolio</mat-card-title>
    <mat-card-content>
      <form [formGroup]="data" (ngSubmit)="submit()">
        <app-form-group label="Title" fcn="title" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="Github Link" fcn="github_link" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="Live Link" fcn="live_link" type="text" [clicked]="clicked"></app-form-group>
        <div>
          <label for="image">Image</label>
          <input (change)="change_file($event)" type="file" accept="image/*" id="image" formControlName="image" style="width: 100%; border: 1px solid gray; padding: 1em; border-radius: .3em">
        </div>
        <div class="align-right" style="margin-top: .75em;">
          <button type="button" mat-raised-button color="warn" (click)="back()">Back</button>
          <button mat-raised-button color="primary">Submit</button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
<app-loading *ngIf="loading"></app-loading>
