// app/src/app/admin/testimonials/new/new.component.ts
import {Component, OnInit} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {PlatformLocation} from "@angular/common";
import {AdminService} from "../../../services/admin.service";

@Component({
  selector: 'app-new',
  templateUrl: './new.component.html',
  styleUrls: ['./new.component.scss']
})
export class NewComponent implements OnInit {
  data: FormGroup = new FormGroup({
    name: new FormControl(null, Validators.required),
    description: new FormControl(null, Validators.required),
    image: new FormControl(null, Validators.required),
  });
  clicked: boolean = false;
  private submitted: Boolean = false;
  loading
    : boolean = false;
  private file!: File;

  constructor(
    private readonly titleService: Title,
    private readonly platformLocation: PlatformLocation,
    private readonly adminService: AdminService,
  ) {
  }

  ngOnInit(): void {
    this.titleService.setTitle('New testimonial');
  }

  onFileChange(event: Event) {
    this.file = (event.target as HTMLInputElement).files!.item(0)!;
  }

  back() {
    this.platformLocation.back();
  }

  submit() {
    this.clicked = true;
    if (this.data.valid && !this.submitted) {
      this.submitted = true;
      this.loading = true;
      let formData = new FormData();
      formData.append('name', this.data.value.name);
      formData.append('description', this.data.value.description);
      formData.append('image', this.file, this.file.name);
      this.adminService.testimonial.new(formData).subscribe({
        next: res => {
          if (res.success) {
            this.back();
          }
          else {
            this.submitted = false;
            this.loading = false;
            alert(res.error);
          }
        },
        error: err => {
          this.loading = false;
          this.clicked = false;
          this.submitted = false;
          console.log(err);
        }
      })
    }
  }
}

<div class="admin-container">
  <mat-card>
    <mat-card-title style="text-align: center;">
      New Testimonial
    </mat-card-title>
    <mat-card-content>
      <form [formGroup]="data" (ngSubmit)="submit()">
        <app-form-group label="Name" fcn="name" type="text" [clicked]="clicked"></app-form-group>
        <app-form-group label="description" fcn="description" type="text" [clicked]="clicked"></app-form-group>
        <div>
          <label for="image">Image</label>
          <input type="file" id="image" formControlName="image" (change)="onFileChange($event)" style="width: 100%; padding: 1em; border: 1px solid gray; border-radius: .3em">
        </div>
        <div class="align-right" style="margin-top: .75em;">
          <button type="button" mat-raised-button color="warn" (click)="back()">Back</button>
          <button mat-raised-button color="primary">Submit</button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
<app-loading *ngIf="loading"></app-loading>

// react-app/src/admin/testimonials/new/new.jsx
import React from "react";
import ReactiveForm from "../../../reactive-form/reactive-form";
import {Link, Navigate} from "react-router-dom";
import FormControl from "../../../reactive-form/form-control";
import Validators from "../../../validators/validators";
import FormGroup from "../../../commons/form-group/form-group";
import AdminService from "../../../services/admin.service";
import UsersService from "../../../services/users.service";

export default class New extends React.Component {

    data = new ReactiveForm({
        name: new FormControl('', [Validators.required]),
        description: new FormControl('', [Validators.required]),
        image: new FormControl('', [Validators.required])
    });


    state = {
        clicked: false,
        loading: false,
        submitted: false,
        go_back: false
    }

    componentDidMount() {
        document.title = 'Admin | Testimonials | New'
    }

    render() {
        return (
            <div id={'new'}>
                {this.state.go_back ? <Navigate to={'../'}/> : null}
                {!UsersService.is_logged_in ? <Navigate to={'/auth/login'}/> : null}
                <div className="container align-center">
                    <div className="card col-md-6 mt-3">
                        <div className="card-header">New Testimonial</div>
                        <div className="card-body">
                            <form onSubmit={e => this.submit(e)}>
                                <FormGroup clicked={this.state.clicked}
                                           name={'Name'}
                                           form_control={this.data.get('name')}
                                />
                                <FormGroup clicked={this.state.clicked}
                                           name={'Description'}
                                           form_control={this.data.get('description')}
                                           className={'mt-3'}
                                />
                                <FormGroup clicked={this.state.clicked}
                                           type={'file'}
                                           name={'image'}
                                           form_control={this.data.get('image')}
                                           className={'mt-3'}
                                           on_change={e => {
                                               this.image = e.target.files.item(0)
                                           }}
                                />
                                <div className="align-right mt-3">
                                    <Link to={'../'} className={'btn'}>Back</Link>
                                    <button type={'submit'} className={'btn btn-primary'}>Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    /**
     * @param {Event<HTMLFormElement>} e
     */
    submit(e) {
        e.preventDefault()
        this.setState({clicked: true}, () => {
            if (this.data.valid && !this.state.submitted && this.image) {
                this.setState({submitted: true, loading: true}, () => {
                    const form_data = new FormData();
                    for (let name in this.data.value) {
                        if (name === 'image') continue;
                        form_data.append(name, this.data.value[name]);
                    }
                    form_data.append('image', this.image, this.image.name);
                    AdminService.testimonials.new(form_data).then(r => {
                        if (r.success) {
                            this.setState({go_back: true});
                        } else {
                            console.log(r);
                            this.setState({submitted: false, loading: false});
                        }
                    });
                });
            }
        });
    }

    /**
     * @type {File}
     */
    image
}
