// react-app/src/admin/header-image/header-image.jsx
import React from "react";
import {Link} from "react-router-dom";
import Loading from "../../commons/loading/loading";
import AdminService from "../../services/admin.service";
import Config from "../../Config";

export default class HeaderImage extends React.Component {
    state = {
        loading: true,
        header_image: null
    }

    componentDidMount() {
        document.title = 'Admin | Header Image'
        AdminService.headerImage.index().then(res => {
            this.setState({loading: false, header_image: res.url});
        });
    }

    render() {
        return (
            <div id="header-image">
                <div className="container">
                    <h1 className={'align-center mt-3'}>Header Image</h1>
                    <div className="align-right mt-3">
                        <Link to={'../'} className={'btn btn-primary'}>Back</Link>
                    </div>
                    {this.state.header_image ? <img src={Config.api + this.state.header_image} alt="Broken Header Image"
                                                    className={'mt-3'}/> : null}
                    <div className="align-center mt-3">
                        <label htmlFor={'file'} className={'btn btn-primary'}>Upload</label>
                        <input onChange={e => this.upload(e)} type="file" id={'file'} accept={'image/*'}
                               style={{display: 'none'}}/>
                        {this.state.header_image ?
                            <button className={'btn'} onClick={this.delete.bind(this)}>Remove</button> : null}
                    </div>
                </div>
                {this.state.loading ? <Loading/> : null}
            </div>
        )
    }

    delete() {

        if (window.confirm('Are you sure you want to delete this photo?')) {
            this.setState({loading: true}, () => {
                AdminService.headerImage.delete().then(res => {
                    if (res.success) {
                        this.setState({loading: false, header_image: null});
                    }
                });
            });
        }
    }

    /**
     * @param {Event} event
     */
    upload(event) {
        this.setState({loading: true, header_image: null}, () => {
            /**
             * @type File
             */
            const file = event.target.files.item(0);
            const form_data = new FormData();
            form_data.append('file', file, file.name);
            AdminService.headerImage.upload(form_data).then(r => {
                if (r.success) {
                    this.setState({loading: false, header_image: r.url});
                }
            });
        });
    }
}

// app/src/app/admin/header-image/header-image.component.ts
import {Component, OnInit} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {AdminService} from "../../services/admin.service";
import {PlatformLocation} from "@angular/common";
import {environment} from "../../../environments/environment";

@Component({
  selector: 'app-header-image',
  templateUrl: './header-image.component.html',
  styleUrls: ['./header-image.component.scss']
})
export class HeaderImageComponent implements OnInit {
  data: FormGroup = new FormGroup({
    image: new FormControl(null, [Validators.required]),
  });
  private submitted: Boolean = false;
  loading: boolean = true;
  url: string = '';
  api: string = environment.api;

  constructor(
    private readonly title: Title,
    private readonly adminService: AdminService,
    private readonly platformLocation: PlatformLocation
  ) {
  }

  ngOnInit(): void {
    this.title.setTitle('Header Image');
    const formData = new FormData();
    formData.append('state', 'get');
    this.adminService.headerImage(formData).subscribe({
      next: (res) => {
        this.url = res.url!;
        this.loading = false;
      },
      error: (err) => {
        console.error(err);
      }
    });
  }


  change_file(event: Event) {
    const file = (<HTMLInputElement>event.target).files?.item(0);
    const formData = new FormData();
    if (file) {
      formData.append('image', file, file.name);
    }
    formData.append('state', 'set')
    if (this.data.valid && !this.submitted) {
      this.submitted = true;
      this.loading = true;
      this.adminService.headerImage(formData).subscribe({
        next: (res) => {
          if (res.success) {
            this.back();
          }else{
            this.submitted = false;
            this.loading = false;
            console.error(res);
          }
        },
        error: (err) => {
          console.error(err);
          this.loading = false;
          this.submitted = false;
        }
      });
    }
  }

  back() {
    this.platformLocation.back();
  }
}

<div class="admin-container">
  <div class="align-right">
    <button (click)="back()" mat-raised-button color="warn">Back</button>
  </div>
  <h2 style="text-align: center">{{'header image' | titlecase}}</h2>
  <form [formGroup]="data">
    <img src="{{api}}{{url}}" alt="">
    <input type="file" style="display: none" accept="image/*" formControlName="image" #file
           (change)="change_file($event)">
    <div class="align-center" style="margin-top: .75em;">
      <button mat-raised-button color="primary" type="button"
              (click)="file.click()">{{url ? 'Update' : 'Upload'}}</button>
    </div>
  </form>
</div>
<app-loading *ngIf="loading"></app-loading>
